export const SAMPLE_CITIZENS = [
  {
    nik: "2105010107750002",
    name: "ZAINUL BAHRI",
    gender: "Laki-laki",
    birthPlace: "BT.TAMBUN",
    birthDate: "1974-07-10",
    education: "TAMAT SD/SEDERAJAT",
    occupation: "BURUH TANI /PERKEBUNAN",
    familyHead: "ZAINUL BAHRI",
    economicStatus: "Prasejahtera",
    address: "Rintis",
    rt: "001",
    rw: "001",
    dusun: "Dusun I Batu Tambun"
  },
  {
    nik: "2105014107780001",
    name: "JUMIATI",
    gender: "Perempuan",
    birthPlace: "TERAP",
    birthDate: "1978-07-01",
    education: "TAMAT SD/SEDERAJAT",
    occupation: "MENGURUS RUMAH TANGGA",
    familyHead: "ZAINUL BAHRI",
    economicStatus: "Prasejahtera",
    address: "Rintis",
    rt: "001",
    rw: "001",
    dusun: "Dusun I Batu Tambun"
  },
  {
    nik: "2105014507000002",
    name: "JULIYANA",
    gender: "Perempuan",
    birthPlace: "TAREMPA",
    birthDate: "2002-07-08",
    education: "BELUM TAMAT SD/SEDERAJAT",
    occupation: "PELAJAR/MAHASISWA",
    familyHead: "ZAINUL BAHRI",
    economicStatus: "Prasejahtera",
    address: "Rintis",
    rt: "001",
    rw: "001",
    dusun: "Dusun I Batu Tambun"
  },
  {
    nik: "2105016204060002",
    name: "JUMILA",
    gender: "Perempuan",
    birthPlace: "AIR BURUT",
    birthDate: "2006-04-22",
    education: "TIDAK/BLM SEKOLAH",
    occupation: "BELUM/TIDAK BEKERJA",
    familyHead: "ZAINUL BAHRI",
    economicStatus: "Prasejahtera",
    address: "Rintis",
    rt: "001",
    rw: "001",
    dusun: "Dusun I Batu Tambun"
  },
  {
    nik: "2105011007770001",
    name: "SAHRONI",
    gender: "Laki-laki",
    birthPlace: "RINTIS",
    birthDate: "1970-07-10",
    education: "TAMAT SD/SEDERAJAT",
    occupation: "PETANI/PEKEBUN",
    familyHead: "SAHRONI",
    economicStatus: "Mampu",
    address: "Rintis",
    rt: "001",
    rw: "001",
    dusun: "Dusun I Batu Tambun"
  },
  {
    nik: "2105010505640001",
    name: "ZAKARIA",
    gender: "Laki-laki",
    birthPlace: "RINTIS",
    birthDate: "1964-05-05",
    education: "TAMAT SD/SEDERAJAT",
    occupation: "PETANI/PEKEBUN",
    familyHead: "ZAKARIA",
    economicStatus: "Mampu",
    address: "Rintis",
    rt: "002",
    rw: "001",
    dusun: "Dusun I Batu Tambun"
  },
  {
    nik: "2105015012690001",
    name: "SUKMINI",
    gender: "Perempuan",
    birthPlace: "RINTIS",
    birthDate: "1969-12-10",
    education: "TAMAT SD/SEDERAJAT",
    occupation: "MENGURUS RUMAH TANGGA",
    familyHead: "ZAKARIA",
    economicStatus: "Mampu",
    address: "Rintis",
    rt: "002",
    rw: "001",
    dusun: "Dusun I Batu Tambun"
  },
  {
    nik: "2105012106600001",
    name: "R.SAHRION",
    gender: "Laki-laki",
    birthPlace: "TELUK RAMBUT",
    birthDate: "1960-08-21",
    education: "SLTP/SEDERAJAD",
    occupation: "PETANI/PEKEBUN",
    familyHead: "R.SAHRION",
    economicStatus: "Mampu",
    address: "Teluk Rambut",
    rt: "003",
    rw: "002",
    dusun: "Dusun II Gudang Tengah Rintis"
  },
  {
    nik: "2105011811850001",
    name: "AZMAN",
    gender: "Laki-laki",
    birthPlace: "LADAN",
    birthDate: "1985-11-18",
    education: "SLTP/SEDERAJAD",
    occupation: "PETANI/PEKEBUN",
    familyHead: "AZMAN",
    economicStatus: "Mampu",
    address: "Ladan",
    rt: "004",
    rw: "002",
    dusun: "Dusun II Gudang Tengah Rintis"
  }
];
